name: Build container

on:
  push:
    branchs:
      - main
  pull_request:
    branchs:
      - main


jobs:
  push-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
        with:
          ref: main
          fetch-depth: 1
      - name: Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/you-bowen/wms-front:v1
